#pragma once
#include <JuceHeader.h>

//==============================================================================
/*  The rotary knob filmstrip (resources/knob-azazel-192x61.png, embedded via
    juce_add_binary_data), and the resampling cache that draws it at whatever
    size a knob happens to be.

    The asset is generated by scripts/make_knob_filmstrip.py, which also proves
    its own output: the ambient shadow, bezel, cast shadow and specular rim are
    byte-identical across all 61 frames (they are baked once, in world space,
    against a light fixed at 315 deg), while only the spun cap grain and the
    etched indicator rotate. That split is what makes the knob read as a
    physical object in a lit room rather than a rotating sticker, and it is why
    nothing here ever applies a rotation transform to the image.

    One 192 px master ships; every on-screen size is derived from it at runtime
    and cached. See boxDownsample() in the .cpp for why that isn't left to
    Graphics::drawImage.
*/
namespace KnobStrip
{
    /** Frames in the embedded strip. */
    constexpr int kFrames = 61;

    /** The strip is baked for JUCE's default rotary sweep (1.25pi .. 2.75pi,
        i.e. 270 deg), which every rotary in this plugin uses -- none of them
        call setRotaryParameters. A knob that did would get an etched pointer
        disagreeing with its own graduation ticks, so draw() asserts on it. */
    constexpr float kSweepRadians = juce::MathConstants<float>::pi * 1.5f;

    /** Where the bezel's outer edge sits, as a fraction of the frame's half
        width. Chrome drawn outside the knob (ticks, value arcs) should be
        placed off this rather than off the frame edge, since the frame also
        carries the ambient shadow and a clear margin beyond it. */
    constexpr float kBezelOuterFrac = 54.0f / 64.0f;

    /** ...and where the ambient shadow finally fades out. Anything drawn
        inside this radius will be sitting in the knob's own shadow. */
    constexpr float kShadowOuterFrac = 59.0f / 64.0f;

    /** Draw a fully procedural metallic knob when the filmstrip asset is not
        available. This is intentionally style-matched to the reference image: a
        black outer shell, knurled dark ring, brushed aluminium cap, and a thin
        vertical indicator. */
    void drawMetallicFallback (juce::Graphics& g, juce::Rectangle<float> dest, float pos);

    /** Draws the frame nearest `pos` (0 = min, 1 = max) into `dest`.

        Returns false if the asset could not be decoded, so the caller can fall
        back to drawing something rather than nothing.
    */
    bool draw (juce::Graphics& g, juce::Rectangle<float> dest, float pos);
}
